#@data/values-schema
---
#! Namespace should be the same as cert-manager's namespace
certmanager:
  namespace: cert-manager
ingress:
  namespace: projectcontour
  ingress_class: contour
tlsdelegation:
  targetns:
  - "*"

domain: ""
wildcard_domain: ""

certs_use: "" #! One of aws, local_ca, provided

#! Aws credentials for IAM user with privileges to use cert-manager DNS01
aws:
  access_key_id: ""
  secret_access_key: ""
  certs:
    region: eu-west-1
    email: user@none.com #! If you want to get notified by Let's encrypt of certificate expiration

local:
  root_ca:
    crt: ""
    key: ""

provided:
  wildcard_tls:
    crt: ""
    key: ""