---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: 1.1.0
            url: quay.io/failk8s/certs-package:1.1.0
        url: quay.io/failk8s/certs-package@sha256:432479be08716db9f6a73368e4ee1ee89f3c3e635707467a587a688f3f1ffe30
  name: certs.dev.failk8s.com.1.1.0
spec:
  refName: certs.dev.failk8s.com
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/certs-package@sha256:432479be08716db9f6a73368e4ee1ee89f3c3e635707467a587a688f3f1ffe30
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  version: 1.1.0
